### ISSUE TITLE
Tests randomly failing

### ISSUE THREAD

**Issue by lutangar** [apivideo/nodejs-sdk#16]
Sometimes testing the number of item fetched from the mock API, one or more tests randomly fails :

```
      AssertionError: expected [ Array(193) ] to have a length of 293 but got 193
      + expected - actual

      -193
      +293
```

I've been able to track this issue down to a race condition occurring while testing the `lastRequest` on search without parameters :
```
    it('Sends good request', () => {
      client.videos.search(parameters);
      expect(client.videos.browser.lastRequest).to.deep.equal({
        url: 'https://ws.api.video/videos?pageSize=100&currentPage=1',
        method: 'GET',
        headers: {},
        json: true,
      });
    });
```

Since we don't wait for this request to complete, this can potentially lead unintended effect.

In the present case, this query can reach the mocked API at the same time than the following request, messing up with the query params. 

This could be fixed with a distinct mocked API for this request. But I think this could lead to other problems :

Since the `video.search` method will make one call per page, we can't assume the `lastRequest` will be the one for the first page. 
BUT one thing we could test for sure (and that I'm favor of) is the following :

If we `await` search method to complete the `lastRequest` would be the request fetching the last page `https://ws.api.video/videos?currentPage=3&pageSize=25'.

**Comment by anthony-dantard** [comment]
I'm ok with the proposal, we can await the search method to complete the lastRequest.
