### ISSUE TITLE
Consider moving to Typescript

### ISSUE THREAD

**Issue by lutangar** [apivideo/nodejs-sdk#21]

**Comment by anthony-dantard** [comment]
Agree with that.

**Comment by LucienLee** [comment]
how about adding the definition file first?

**Comment by lutangar** [comment]
A new __major version_ of the nodejs-client is available at https://github.com/apivideo/nodejs-api-client
Since this is a major version it isn't backward compatible and may be subject to new bugs.
The good news is it supports Typescript by design !

> This is part of greater effort to generate the new clients based on the [Api.Video OpenAPI Specification](https://github.com/apivideo/API_OAS_file) file.
