### ISSUE TITLE
Un-consistent return type in get/search methods

### ISSUE THREAD

**Issue by lutangar** [apivideo/nodejs-sdk#22]
Sometimes if the response is not successful the response is rejected alright, but reject parameters should me an `Error`:
```
      if (!that.browser.isSuccessfull(response)) {
        reject(response);
      }
```

Sometimes nothing is done, I wonder what the result would be :
```
    /* eslint-disable no-await-in-loop */
    do {
      const response = await this.browser.get(
        `/videos?${httpBuildQuery(params)}`,
      );

      if (that.browser.isSuccessfull(response)) {
        const results = response.body;
        const videos = results.data;
        allVideos.push(that.castAll(videos));

        if (typeof parameters.currentPage !== 'undefined') {
          break;
        }

        ({ pagination } = results);
        pagination.currentPage += 1;
        params.currentPage = pagination.currentPage;
      } // nothing here
    } while (pagination.pagesTotal > pagination.currentPage);
```

And sometimes whereas the promise should be returned, the response is returned :
```
      if (!that.browser.isSuccessfull(response)) {
        return response;
      }
```

A common strategy should be put in place to tackle these inconsistencies.

**Comment by anthony-dantard** [comment]
I think we have to throw an Error/Exception rather than silencing the errors. Maybe we should build and throw a ApiVideoException to handle response error from the web-services. The API can sent different Problem Detail when a request is malformed or for common errors. (https://docs.api.video/5.1/problems)
