### ISSUE TITLE
Chunks created on-disk before upload

### ISSUE THREAD

**Issue by gdyr** [apivideo/nodejs-sdk#23]
Before uploading a video file, chunks are created on disk.
This requires the video file's size to be available in the system's temporary directory.
For large files, or systems with a small /tmp directory, this is not a safe assumption.

I'd suggest reading the relevant section of the original video file into the request, for example using readSync() rather than readFileSync().

Happy to submit a PR to this effect.

**Comment by dougsillars** [comment]
we'd happily accept this PR.  Thank you.

**Comment by anthony-dantard** [comment]
Hi,

Thank you very much for your pull request. We tested it and merged it in the master branch. The new version is released on npm with release 1.8.5.
