### ISSUE TITLE
TypeError: fs.existsSync is not a function

### ISSUE THREAD

**Issue by tycooperaow** [apivideo/nodejs-sdk#3]
I keep getting this error 'TypeError: fs.existsSync is not a function'
from the following:

```
const client = new apiVideo.ClientSandbox({ apiKey: 'my-api-key' });
          let result = client.videos.upload('@/assets/media/EZ.MOV', {title: 'Ez'});
          result.then(function(video) {
            console.log(video.title);
          }).catch(function(error) {
            console.error(error);
          });
```

**Comment by dougsillars** [comment]
Hi there, 
You want to have the exact path for the video in the upload. (I think removing the @ from the path will fix your issue.)
In my example https://github.com/dougsillars/DougsUglyUploader
I upload the file with a form, and then use Formidable to save the file.
My Client call looks like:
```
	let result = client.videos.upload(files.source.path, {title: videoTitle});
```
Let me know if that gets you further along!

**Comment by tycooperaow** [comment]
New issue, when my video gets uploaded it just says, "this video is being processed". Even though none of my videos are processed.

**Comment by lutangar** [comment]
> New issue, when my video gets uploaded it just says, "this video is being processed". Even though none of my videos are processed.

If this is still relevant, please post a new issue (hope your videos were finally processed tho' :wink: )
