### ISSUE TITLE
README.md should be correct also for AnalyticsVideo

### ISSUE THREAD

**Issue by mlc-mlapis** [apivideo/nodejs-sdk#43]
The same problem with a wrong API description also exists for `AnalyticsVideo`. It's necessary to update it in the same way as for `AnalyticsLive`.

![image](https://user-images.githubusercontent.com/5693835/108524782-b11a0000-72cf-11eb-8d65-d066494a87cd.png)

**Comment by lutangar** [comment]
Nice catch @mlc-mlapis thanks for reporting.
