### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by lutangar** [apivideo/nodejs-sdk#6]
When `isStillAuthenticated` method is called in `browser.js`, if the "last request" has no headers, the `Object.keys` method fails :

Here's the content of the `lastRequest` object when the failure occurs :
```
lastRequest {
  url: 'https://ws.api.video/auth/api-key',
  body: { apiKey: 'XXXX' },
  json: true
}
```

And the error :
```
(node:5730) UnhandledPromiseRejectionWarning: TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Browser.isStillAuthenticated (/node_modules/@api.video/nodejs-sdk/lib/Browser/browser.js:64:14)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Request._callback (/node_modules/@api.video/nodejs-sdk/lib/Browser/browser.js:113:24)
(node:5730) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5730) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by lutangar** [comment]
After digging a bit, as in #16 the problem seems to come from concurrent calls. 
The `lastRequest` mechanism is not reliable as it is, we can't assert that the `lastRequest` is what we're expected since it could have been modified by another concurrent request.

Hence in `isStillAuthenticated` method of the `Browser`, the `lastRequest` might be a call to the the access token endpoint :
```
      this.lastRequest = {
        url: `${that.baseUri}/auth/api-key`,
        body: {
          apiKey: that.apiKey,
        },
        json: true
      };
```

Which have no headers. 

A quickfix might be adding an empty `headers` property, but that wouldn't solve the problem of concurrency and the reliability of the `lastRequest`.

The `Browser` code fully rely on `lastRequest` to recall the last unauthorized request with the new token.

**Comment by lutangar** [comment]
After some more digging here are my suggestions :

As previously highlighted the `lastRequest` mechanism is flawed :
> The `lastRequest` mechanism is not reliable as it is, we can't assert that the `lastRequest` is what we're expected since it could have been modified by another concurrent request.

That being said, it also means that some APIs calls are just lost and won't get another chance. 

My first suggestion would be to check the validity of the access token before each request, with a high margin of error, it could mitigates most expiration issues. Let's say we renew the access token 5mins before it expires we won't experience a `401` error -- except we might -- if another request is made before we retrieve the new access token, this request would probably fail right?
This would depends on the authentication server implementation. When an `access_token` is renewed, would the previous `access_token` be valid if it's still in its 1hour validity period?

If that the case one good enough solution, might be to intercept failing request (`401`) and trigger a token refresh each time. That would lead to extra refresh request but might not be a problem depending on the authentication server implementation.

Another better solution would be an "async" **queue**. This queue could keep tracks of every unsuccessful requests. 
When a `401` error is reach, this would trigger a refresh token request - only if none is pending -  and all ongoing and subsequent requests would be "paused". 
Once the token is fresh, all paused requests would be run back in parallel. 
This might need some time to implements and [rxjs](https://www.learnrxjs.io/) might help to orchestrate this async workflow.

**Comment by ikovac** [comment]
I have the same problem. What is the status of this issue?

**Comment by lutangar** [comment]
This is now a work in progress.
